-- pg_partman was here until Phase 4 of docs/features/09-clickhouse.md. It
-- existed for one table — the daily-partitioned `events` — which now lives in
-- ClickHouse, partitioned monthly by the engine. Removing it also removed the
-- custom `db/Dockerfile` this directory existed to build: both compose files
-- run stock `postgres:16` again.
--
-- An existing install keeps the extension objects; they are inert and can be
-- dropped by hand along with the `events` table.

-- Query-level statistics. Requires `shared_preload_libraries=pg_stat_statements`,
-- which both compose files pass on the postgres command line.
--
-- The app's own slow-query logger (core/db/middleware/slow-query-logger.ts)
-- only reports queries over 500 ms, so it cannot see an 80 ms query called two
-- hundred times a minute — which is what the read path actually looks like.
-- This fills that gap.
--
-- NOTE: this file runs only against the container's default database (POSTGRES_DB)
-- and only on an empty data directory. An existing install needs it once by hand:
--   docker compose exec postgres psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
--     -c 'CREATE EXTENSION IF NOT EXISTS pg_stat_statements'
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
