/**
 * test-exempt: entrypoint. Calls `main()` at module scope and `process.exit(1)`
 * on failure, so importing it in a test would run it. The work it orchestrates
 * lives in `core/db/apply-schema.ts`, which is covered by `apply-schema.test.ts`
 * — that split is deliberate and its reasoning is in that file's header. What is
 * left here is wiring: which clients, which order, what to log. Guarding the
 * call with `require.main === module` would make this importable at the cost of
 * a bundler quirk being able to turn the bootstrap into a silent no-op, which
 * is a far worse failure than an untested five-line function.
 *
 * Entrypoint for the one-shot `bootstrap` container — and the only thing that
 * creates schema, anywhere.
 *
 * **There are no migrations.** Replaced 2026-08-26, when `events` moved to
 * ClickHouse (docs/features/09-clickhouse.md): there is no deployed data, the
 * Postgres schema is about to lose its largest table, and a sixteen-file chain
 * describing how it got here was carrying the cost of history nobody has.
 * Each store instead has one file describing its end state, applied whole:
 *
 *   db/schema.sql              — Postgres, generated by scripts/build-schema.mjs
 *   core/clickhouse/schema.sql — ClickHouse, hand-written
 *
 * Both are idempotent, so this runs on every start rather than only on a fresh
 * database. Bundled to `bootstrap.js` by `scripts/build-worker.mjs` and run as
 * `node bootstrap.js`; compose gates `app` and `worker` on its exit code via
 * `condition: service_completed_successfully`.
 *
 * **The cost, stated plainly**: a schema change against a database holding real
 * rows has no upgrade path — the drop/recreate that makes this simple is only
 * safe while nothing is deployed. That has to be reconsidered before the first
 * install anybody depends on. PLAN.md §17 names that condition.
 */
import postgres from "postgres";
import { env } from "@/core/env";
import { logger } from "@/core/logger";
import { clickhouse } from "@/core/clickhouse/client";
import { splitDdl } from "@/core/clickhouse/ddl";
import { applyPostgresSchema, applyClickhouseSchema } from "@/core/db/apply-schema";

/**
 * Where the two `.sql` files live. Overridden in the image, where they are
 * copied next to the bundle under their repo-relative paths — the paths are
 * kept rather than flattened so one pair of strings works in both places.
 */
const SCHEMA_DIR = process.env.SCHEMA_DIR ?? ".";

async function main(): Promise<void> {
    // A dedicated single connection, not the pooled `core/db/client` singleton:
    // this runs once and the process exits straight afterwards.
    const sql = postgres(env.DATABASE_URL, { max: 1 });

    try {
        const file = await applyPostgresSchema(sql, SCHEMA_DIR);
        logger.info({ file }, "postgres schema applied");
    } finally {
        await sql.end();
    }

    const result = await applyClickhouseSchema(clickhouse, SCHEMA_DIR, splitDdl);
    logger.info(result, "clickhouse schema applied");

    await clickhouse.close();
}

main().catch((err) => {
    logger.fatal({ err }, "bootstrap failed");
    process.exit(1);
});
