import { describe, it, expect } from "vitest";
import { splitStatements, makeIdempotent, assembleSchema } from "./build-schema.mjs";

describe("splitStatements", () => {
    it("splits on semicolons and trims", () => {
        expect(splitStatements('CREATE TABLE "a" ();\n\nCREATE TABLE "b" ();')).toEqual([
            'CREATE TABLE "a" ()',
            'CREATE TABLE "b" ()',
        ]);
    });

    it("does not split inside a $$-quoted body", () => {
        const sql = 'DO $$ BEGIN PERFORM 1; PERFORM 2; END $$;\nCREATE TABLE "b" ();';
        expect(splitStatements(sql)).toEqual([
            "DO $$ BEGIN PERFORM 1; PERFORM 2; END $$",
            'CREATE TABLE "b" ()',
        ]);
    });

    it("keeps a final statement that has no trailing semicolon", () => {
        expect(splitStatements('CREATE TABLE "a" ()')).toEqual(['CREATE TABLE "a" ()']);
    });

    it("returns nothing for empty or whitespace-only input", () => {
        expect(splitStatements("")).toEqual([]);
        expect(splitStatements("  \n\n ;; \n")).toEqual([]);
    });
});

/**
 * `stripEventsStatements` was deleted in Phase 4 along with its three tests.
 * It dropped every `"events"` statement out of the generated DDL so
 * `db/events.sql` could be spliced in, and its one subtlety — matching the
 * *quoted* identifier, so that `"event_rollup_minutes"` survived — has no
 * subject left: events are in ClickHouse and the rollup tables are gone too.
 * Everything in `db/schema.sql` is generated now.
 */
describe("assembleSchema", () => {
    it("emits every generated statement, guarded", () => {
        const out = assembleSchema('CREATE TABLE "users" ("id" text);\nCREATE TABLE "a" ();');

        expect(out).toContain(`CREATE TABLE IF NOT EXISTS "users" ("id" text);`);
        expect(out).toContain(`CREATE TABLE IF NOT EXISTS "a" ();`);
    });

    it("keeps an events table out of the baseline by never being given one", () => {
        // The assertion is about the *input* now, not about a filter: nothing
        // in `core/db/schema/` defines `events`, so nothing can generate it. If
        // a Drizzle table for events is ever re-added, this fails and the
        // failure is the right one — the question would be why it came back.
        const out = assembleSchema('CREATE TABLE "users" ("id" text);');
        expect(out).not.toContain('"events"');
    });

    it("marks the output as generated so nobody hand-edits it", () => {
        const out = assembleSchema('CREATE TABLE "users" ("id" text);');
        expect(out).toMatch(/^-- GENERATED by scripts\/build-schema\.mjs/);
    });

    it("says where events went, so the absence reads as a decision", () => {
        const out = assembleSchema('CREATE TABLE "users" ("id" text);');
        expect(out).toContain("core/clickhouse/schema.sql");
    });
});

describe("makeIdempotent", () => {
    it("guards CREATE TABLE", () => {
        expect(makeIdempotent('CREATE TABLE "users" (\n\t"id" text\n)')).toBe(
            'CREATE TABLE IF NOT EXISTS "users" (\n\t"id" text\n)',
        );
    });

    it("guards CREATE INDEX and keeps UNIQUE in place", () => {
        expect(makeIdempotent('CREATE INDEX "a_idx" ON "a" USING btree ("x")')).toBe(
            'CREATE INDEX IF NOT EXISTS "a_idx" ON "a" USING btree ("x")',
        );
        expect(makeIdempotent('CREATE UNIQUE INDEX "a_uq" ON "a" USING btree ("x")')).toBe(
            'CREATE UNIQUE INDEX IF NOT EXISTS "a_uq" ON "a" USING btree ("x")',
        );
    });

    it("wraps ADD CONSTRAINT, which has no IF NOT EXISTS form", () => {
        const out = makeIdempotent(
            'ALTER TABLE "a" ADD CONSTRAINT "a_fk" FOREIGN KEY ("b") REFERENCES "public"."b"("id")',
        );
        expect(out).toMatch(/^DO \$\$ BEGIN/);
        expect(out).toContain('ALTER TABLE "a" ADD CONSTRAINT "a_fk"');
        expect(out).toContain("EXCEPTION WHEN duplicate_object THEN NULL;");
    });

    it("leaves anything else alone", () => {
        expect(makeIdempotent('ALTER TABLE "a" ALTER COLUMN "b" SET NOT NULL')).toBe(
            'ALTER TABLE "a" ALTER COLUMN "b" SET NOT NULL',
        );
    });

    /**
     * The wrapped constraint introduces the first `$$` body into the baseline.
     * If the splitter and the wrapper disagree, the file re-parses into
     * fragments that each fail on their own — so they are checked together.
     */
    it("produces output the splitter can round-trip", () => {
        const wrapped = makeIdempotent('ALTER TABLE "a" ADD CONSTRAINT "a_fk" FOREIGN KEY ("b")');
        expect(splitStatements(`${wrapped};`)).toEqual([wrapped]);
    });
});
