/**
 * Regenerates `db/schema.sql` — the from-zero Postgres baseline.
 *
 * There is no migration chain any more (docs/features/09-clickhouse.md, and
 * PLAN.md §17 2026-08-26). The database is built from empty, so the schema is
 * one file describing the end state rather than sixteen describing a path to
 * it. `drizzle-kit export` produces that file from `core/db/schema/`, which
 * makes the Drizzle definitions the single source of truth.
 *
 * **Everything here is now generated.** Until Phase 4 this script also stripped
 * every `"events"` statement out of the generated DDL and spliced
 * `db/events.sql` in by hand, because partitioning, the composite primary key
 * it forces, the GIN indexes and the pg_partman registration all live outside
 * the Drizzle DSL. Events are in ClickHouse; that table, that file and the
 * splice are gone, and `core/clickhouse/schema.sql` is the hand-written
 * counterpart on the other side.
 *
 * **Never hand-edit `db/schema.sql`.** Change `core/db/schema/*.ts` and re-run
 * this. Migration 0003 was a hand-edit inside a generated file and survived
 * only because nothing ever regenerated it.
 *
 * Usage: npm run db:schema
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Splits generated DDL into statements.
 *
 * `$$`-quoted bodies are tracked because a `DO $$ … END $$;` block holds
 * semicolons that do not end a statement. `drizzle-kit export` emits none
 * today, but this function also runs over hand-written SQL in the tests, and a
 * splitter that is wrong only on the input it does not currently see is the
 * kind that breaks silently later.
 */
export function splitStatements(sql) {
    const statements = [];
    let current = "";
    let inDollarQuote = false;

    for (let i = 0; i < sql.length; i++) {
        const char = sql[i];

        if (char === "$" && sql[i + 1] === "$") {
            inDollarQuote = !inDollarQuote;
            current += "$$";
            i++;
            continue;
        }

        if (char === ";" && !inDollarQuote) {
            statements.push(current.trim());
            current = "";
            continue;
        }

        current += char;
    }

    const trailing = current.trim();
    if (trailing !== "") statements.push(trailing);

    return statements.filter((s) => s !== "");
}

/**
 * Rewrites one generated statement so re-applying the baseline is a no-op.
 *
 * The bootstrap runs the whole file on every start — dev, e2e, itest and the
 * one-shot container — so "already exists" has to be the normal case, not an
 * error to be caught and guessed at. `drizzle-kit export` describes an empty
 * database and emits none of these guards.
 *
 * `ADD CONSTRAINT` has no `IF NOT EXISTS` form in any Postgres version, hence
 * the exception block rather than a fifth regex.
 */
export function makeIdempotent(statement) {
    const s = statement.trim();

    if (/^CREATE TABLE\s+"/.test(s)) {
        return s.replace(/^CREATE TABLE\s+/, "CREATE TABLE IF NOT EXISTS ");
    }

    if (/^CREATE (UNIQUE )?INDEX\s+"/.test(s)) {
        return s.replace(/^CREATE (UNIQUE )?INDEX\s+/, (_, unique) =>
            `CREATE ${unique ?? ""}INDEX IF NOT EXISTS `,
        );
    }

    if (/^ALTER TABLE\s+.*\bADD CONSTRAINT\b/s.test(s)) {
        return `DO $$ BEGIN\n    ${s};\nEXCEPTION WHEN duplicate_object THEN NULL;\nEND $$`;
    }

    return s;
}

/** The generated DDL, made idempotent. */
export function assembleSchema(generatedSql) {
    const kept = splitStatements(generatedSql).map(makeIdempotent);

    return [HEADER, kept.map((s) => `${s};`).join("\n\n"), ""].join("\n");
}

const HEADER = `-- GENERATED by scripts/build-schema.mjs — do not edit.
--
-- The complete Postgres schema, built from empty. There are no migrations:
-- see docs/reference/architecture.md. Regenerate with \`npm run db:schema\`
-- after changing core/db/schema/*.ts.
--
-- Events are not here: they live in ClickHouse (core/clickhouse/schema.sql).
--
-- Applied by core/db/bootstrap.ts (dev, e2e, itest and the one-shot
-- \`bootstrap\` container). Every statement is idempotent.
`;

function main() {
    // drizzle-kit's own entrypoint, not `npx`: `npx.cmd` cannot be spawned
    // without a shell on Windows (EINVAL), and resolving the package here keeps
    // the script behaving identically on every platform.
    // Resolved from the package entry rather than as a `drizzle-kit/bin.cjs`
    // subpath, which its `exports` map does not expose.
    const drizzleKitBin = path.join(
        path.dirname(createRequire(import.meta.url).resolve("drizzle-kit")),
        "bin.cjs",
    );
    const generated = execFileSync(
        process.execPath,
        [drizzleKitBin, "export", "--sql"],
        { cwd: rootDir, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
    );

    // drizzle-kit prints a banner line about injected env files before the DDL.
    const ddl = generated.slice(generated.search(/^CREATE /m));
    if (ddl === "") throw new Error("drizzle-kit export produced no DDL");

    const out = assembleSchema(ddl);

    writeFileSync(path.join(rootDir, "db/schema.sql"), out, "utf8");
    console.log(`db/schema.sql — ${out.split("\n").length} lines`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
